server:
  port: 8081

spring:
  application:
    name: 'provider'
  datasource:
    username: app
    password: passwd
    url: jdbc:mysql://localhost:3306/provider
  jpa:
    hibernate:
      ddl-auto: create
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  